DROP TABLE IF EXISTS CurrencyDetails;

CREATE TABLE CurrencyDetails (
    currency_id INT AUTO_INCREMENT PRIMARY KEY,
    currency_code VARCHAR(10) NOT NULL UNIQUE,
    currency_name VARCHAR(100) NOT NULL,
    symbol VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
);

INSERT INTO CurrencyDetails (currency_code, currency_name, symbol)
VALUES
    ('USD', 'United States Dollar', '$'),
    ('EUR', 'Euro', '€'),
    ('JPY', 'Japanese Yen', '¥'),
    ('GBP', 'British Pound Sterling', '£'),
    ('AUD', 'Australian Dollar', 'A$'),
    ('CAD', 'Canadian Dollar', 'C$'),
    ('CHF', 'Swiss Franc', 'CHF'),
    ('CNY', 'Chinese Yuan', '¥'),
    ('SEK', 'Swedish Krona', 'kr'),
    ('NZD', 'New Zealand Dollar', 'NZ$'),
    ('MXN', 'Mexican Peso', '$'),
    ('SGD', 'Singapore Dollar', 'S$'),
    ('HKD', 'Hong Kong Dollar', 'HK$'),
    ('NOK', 'Norwegian Krone', 'kr'),
    ('KRW', 'South Korean Won', '₩'),
    ('TRY', 'Turkish Lira', '₺'),
    ('INR', 'Indian Rupee', '₹'),
    ('RUB', 'Russian Ruble', '₽'),
    ('BRL', 'Brazilian Real', 'R$'),
    ('ZAR', 'South African Rand', 'R'),
    ('DKK', 'Danish Krone', 'kr'),
    ('PLN', 'Polish Zloty', 'zł'),
    ('THB', 'Thai Baht', '฿'),
    ('IDR', 'Indonesian Rupiah', 'Rp'),
    ('HUF', 'Hungarian Forint', 'Ft'),
    ('CZK', 'Czech Koruna', 'Kč'),
    ('ILS', 'Israeli New Shekel', '₪'),
    ('CLP', 'Chilean Peso', '$'),
    ('PHP', 'Philippine Peso', '₱'),
    ('AED', 'United Arab Emirates Dirham', 'د.إ'),
    ('MYR', 'Malaysian Ringgit', 'RM'),
    ('SAR', 'Saudi Riyal', '﷼'),
    ('NGN', 'Nigerian Naira', '₦'),
    ('PKR', 'Pakistani Rupee', '₨'),
    ('BDT', 'Bangladeshi Taka', '৳'),
    ('VND', 'Vietnamese Dong', '₫'),
    ('EGP', 'Egyptian Pound', 'E£'),
    ('ARS', 'Argentine Peso', '$'),
    ('KES', 'Kenyan Shilling', 'KSh'),
    ('COP', 'Colombian Peso', '$'),
    ('KZT', 'Kazakhstani Tenge', '₸'),
    ('LKR', 'Sri Lankan Rupee', 'Rs'),
    ('MMK', 'Burmese Kyat', 'K'),
    ('NPR', 'Nepalese Rupee', 'Rs'),
    ('TWD', 'New Taiwan Dollar', 'NT$'),
    ('MAD', 'Moroccan Dirham', 'DH'),
    ('QAR', 'Qatari Rial', '﷼'),
    ('KWD', 'Kuwaiti Dinar', 'د.ك'),
    ('OMR', 'Omani Rial', '﷼'),
    ('BHD', 'Bahraini Dinar', 'ب.د'),
    ('DZD', 'Algerian Dinar', 'دج'),
    ('JOD', 'Jordanian Dinar', 'د.أ'),
    ('IQD', 'Iraqi Dinar', 'ع.د'),
    ('LBP', 'Lebanese Pound', 'ل.ل'),
    ('XOF', 'West African CFA Franc', 'CFA'),
    ('XAF', 'Central African CFA Franc', 'FCFA'),
    ('GHS', 'Ghanaian Cedi', '₵'),
    ('UGX', 'Ugandan Shilling', 'USh'),
    ('TND', 'Tunisian Dinar', 'د.ت'),
    ('XCD', 'East Caribbean Dollar', '$'),
    ('JMD', 'Jamaican Dollar', 'J$'),
    ('TTD', 'Trinidad and Tobago Dollar', 'TT$'),
    ('FJD', 'Fijian Dollar', 'FJ$'),
    ('ZMW', 'Zambian Kwacha', 'ZK'),
    ('MUR', 'Mauritian Rupee', '₨'),
    ('SCR', 'Seychellois Rupee', '₨'),
    ('BBD', 'Barbadian Dollar', 'Bds$'),
    ('BZD', 'Belize Dollar', 'BZ$'),
    ('BMD', 'Bermudian Dollar', '$'),
    ('KYD', 'Cayman Islands Dollar', 'CI$'),
    ('BSD', 'Bahamian Dollar', '$');