# Direct log messages to coretix.log
log4j.logger.com.web.coretix=ALL, coretixFile
# Direct log messages to module.log
log4j.logger.com.module.coretix=ALL, moduleFile
# Direct other log messages to persist.log
log4j.logger.com.persist.coretix=ALL, persistFile
# Coretix log appender
log4j.appender.coretixFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.coretixFile.File=${catalina.base}/logs/coretix/coretix.log
log4j.appender.coretixFile.DatePattern='.'dd_MM_yyyy
log4j.appender.coretixFile.layout=org.apache.log4j.PatternLayout
log4j.appender.coretixFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
# Module log appender
log4j.appender.moduleFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.moduleFile.File=${catalina.base}/logs/coretix/module.log
log4j.appender.moduleFile.DatePattern='.'dd_MM_yyyy
log4j.appender.moduleFile.layout=org.apache.log4j.PatternLayout
log4j.appender.moduleFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
# Persist log appender
log4j.appender.persistFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.persistFile.File=${catalina.base}/logs/coretix/persist.log
log4j.appender.persistFile.DatePattern='.'dd_MM_yyyy
log4j.appender.persistFile.layout=org.apache.log4j.PatternLayout
log4j.appender.persistFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n


