CREATE TABLE IF NOT EXISTS MedicalCertificateSettings (
    id INT NOT NULL AUTO_INCREMENT,
    organization_id INT NOT NULL,
    page_size VARCHAR(20) NOT NULL DEFAULT 'A4',
    template_name VARCHAR(100) NOT NULL DEFAULT 'Classic',
    theme_color VARCHAR(20) NOT NULL DEFAULT '#0F766E',
    text_color VARCHAR(20) NOT NULL DEFAULT '#111827',
    certificate_title VARCHAR(150) NOT NULL DEFAULT 'Medical Certificate',
    intro_line VARCHAR(255) DEFAULT NULL,
    body_paragraph_one VARCHAR(1000) DEFAULT NULL,
    body_paragraph_two VARCHAR(1000) DEFAULT NULL,
    disease_label VARCHAR(80) DEFAULT 'Nature Of Disease',
    treatment_duration_label VARCHAR(80) DEFAULT 'Duration Of Treatment',
    patient_signature_label VARCHAR(80) DEFAULT 'Signature Of Patient',
    place_label VARCHAR(40) DEFAULT 'Place',
    date_label VARCHAR(40) DEFAULT 'Date',
    font_family VARCHAR(50) NOT NULL DEFAULT 'Helvetica',
    font_size INT NOT NULL DEFAULT 12,
    logo_size VARCHAR(20) NOT NULL DEFAULT 'Medium',
    show_clinic_logo BIT NOT NULL DEFAULT b'1',
    show_watermark BIT NOT NULL DEFAULT b'0',
    watermark_text VARCHAR(100) DEFAULT NULL,
    notes VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_medical_certificate_settings_org (organization_id),
    CONSTRAINT fk_medical_certificate_settings_organization FOREIGN KEY (organization_id) REFERENCES Organizations(id)
);
