CREATE TABLE IF NOT EXISTS Consultations (
    id INT NOT NULL AUTO_INCREMENT,
    organization_id INT NOT NULL,
    doctor_id INT NOT NULL,
    patient_id INT NOT NULL,
    consultation_number VARCHAR(40) NOT NULL,
    consultation_date TIMESTAMP NOT NULL,
    token_number INT DEFAULT NULL,
    patient_age_years INT DEFAULT NULL,
    temperature_celsius VARCHAR(20) DEFAULT NULL,
    weight_kg VARCHAR(20) DEFAULT NULL,
    blood_pressure VARCHAR(30) DEFAULT NULL,
    symptoms VARCHAR(2000) DEFAULT NULL,
    family_history VARCHAR(1000) DEFAULT NULL,
    vitals VARCHAR(1000) DEFAULT NULL,
    findings VARCHAR(2000) DEFAULT NULL,
    diagnosis VARCHAR(2000) DEFAULT NULL,
    follow_up_note VARCHAR(500) DEFAULT NULL,
    doctor_notes VARCHAR(2000) DEFAULT NULL,
    issue_invoice BIT NOT NULL DEFAULT b'1',
    issue_medical_certificate BIT NOT NULL DEFAULT b'0',
    invoice_paid_by VARCHAR(80) DEFAULT NULL,
    invoice_issue_date TIMESTAMP NULL DEFAULT NULL,
    invoice_due_date TIMESTAMP NULL DEFAULT NULL,
    medical_certificate_disease VARCHAR(500) DEFAULT NULL,
    medical_certificate_treatment_duration VARCHAR(255) DEFAULT NULL,
    medical_certificate_place VARCHAR(120) DEFAULT NULL,
    consultation_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    medicine_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    medical_certificate_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    invoice_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(30) NOT NULL DEFAULT 'Completed',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_consultations_number (consultation_number),
    KEY idx_consultations_org (organization_id),
    KEY idx_consultations_doctor (doctor_id),
    KEY idx_consultations_patient (patient_id),
    KEY idx_consultations_token (token_number),
    CONSTRAINT fk_consultations_organization FOREIGN KEY (organization_id) REFERENCES Organizations(id),
    CONSTRAINT fk_consultations_doctor FOREIGN KEY (doctor_id) REFERENCES Doctors(id),
    CONSTRAINT fk_consultations_patient FOREIGN KEY (patient_id) REFERENCES Patients(id)
);

CREATE TABLE IF NOT EXISTS ConsultationMedicines (
    id INT NOT NULL AUTO_INCREMENT,
    consultation_id INT NOT NULL,
    medicine_id INT NOT NULL,
    line_number INT NOT NULL,
    description_text VARCHAR(255) NOT NULL,
    dose VARCHAR(100) DEFAULT NULL,
    frequency VARCHAR(120) DEFAULT NULL,
    duration_text VARCHAR(120) DEFAULT NULL,
    remarks VARCHAR(500) DEFAULT NULL,
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_consultation_medicines_consultation (consultation_id),
    KEY idx_consultation_medicines_medicine (medicine_id),
    CONSTRAINT fk_consultation_medicines_consultation FOREIGN KEY (consultation_id) REFERENCES Consultations(id) ON DELETE CASCADE,
    CONSTRAINT fk_consultation_medicines_medicine FOREIGN KEY (medicine_id) REFERENCES Medicines(id)
);
