CREATE TABLE IF NOT EXISTS InvoiceSettings (
    id INT NOT NULL AUTO_INCREMENT,
    organization_id INT NOT NULL,
    page_size VARCHAR(20) NOT NULL DEFAULT 'A4',
    template_name VARCHAR(100) NOT NULL DEFAULT 'Classic',
    theme_color VARCHAR(20) NOT NULL DEFAULT '#0F766E',
    text_color VARCHAR(20) NOT NULL DEFAULT '#111827',
    invoice_title VARCHAR(150) NOT NULL DEFAULT 'Tax Invoice',
    invoice_number_label VARCHAR(80) DEFAULT 'Invoice No',
    bill_from_label VARCHAR(80) DEFAULT 'Bill From',
    bill_to_label VARCHAR(80) DEFAULT 'Bill To',
    issue_date_label VARCHAR(80) DEFAULT 'Issue Date',
    due_date_label VARCHAR(80) DEFAULT 'Due Date',
    paid_by_label VARCHAR(80) DEFAULT 'Paid By',
    description_column_label VARCHAR(80) DEFAULT 'Description',
    quantity_column_label VARCHAR(40) DEFAULT 'Qty',
    price_column_label VARCHAR(40) DEFAULT 'Price',
    total_column_label VARCHAR(40) DEFAULT 'Total',
    grand_total_label VARCHAR(80) DEFAULT 'Grand Total',
    footer_note VARCHAR(255) DEFAULT NULL,
    font_family VARCHAR(50) NOT NULL DEFAULT 'Helvetica',
    font_size INT NOT NULL DEFAULT 12,
    logo_size VARCHAR(20) NOT NULL DEFAULT 'Medium',
    show_clinic_logo BIT NOT NULL DEFAULT b'1',
    show_watermark BIT NOT NULL DEFAULT b'0',
    watermark_text VARCHAR(100) DEFAULT NULL,
    notes VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_invoice_settings_org (organization_id),
    CONSTRAINT fk_invoice_settings_organization FOREIGN KEY (organization_id) REFERENCES Organizations(id)
);
