CREATE TABLE IF NOT EXISTS `PrescriptionSettings` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `organization_id` INT NOT NULL,
    `page_size` VARCHAR(20) NOT NULL DEFAULT 'A4',
    `template_name` VARCHAR(100) NOT NULL DEFAULT 'Classic',
    `theme_color` VARCHAR(20) NOT NULL DEFAULT '#0F766E',
    `text_color` VARCHAR(20) NOT NULL DEFAULT '#111827',
    `header_title` VARCHAR(150) NOT NULL DEFAULT 'Medical Prescription',
    `clinical_notes_label` VARCHAR(80) NULL DEFAULT 'Clinical Notes',
    `symptoms_label` VARCHAR(80) NULL DEFAULT 'Symptoms',
    `family_history_label` VARCHAR(80) NULL DEFAULT 'Family History',
    `vitals_label` VARCHAR(80) NULL DEFAULT 'Vitals',
    `findings_label` VARCHAR(80) NULL DEFAULT 'Findings',
    `diagnosis_label` VARCHAR(80) NULL DEFAULT 'Diagnosis',
    `prescription_label` VARCHAR(80) NULL DEFAULT 'Prescription',
    `medication_column_label` VARCHAR(60) NULL DEFAULT 'Medications',
    `dose_column_label` VARCHAR(60) NULL DEFAULT 'Dose',
    `frequency_column_label` VARCHAR(60) NULL DEFAULT 'Frequency',
    `duration_column_label` VARCHAR(60) NULL DEFAULT 'Duration',
    `remarks_column_label` VARCHAR(60) NULL DEFAULT 'Remarks',
    `follow_up_label` VARCHAR(80) NULL DEFAULT 'Follow Up',
    `footer_note` VARCHAR(255) NULL,
    `font_family` VARCHAR(50) NOT NULL DEFAULT 'Helvetica',
    `font_size` INT NOT NULL DEFAULT 12,
    `logo_size` VARCHAR(20) NOT NULL DEFAULT 'Medium',
    `margin_top_mm` INT NOT NULL DEFAULT 12,
    `margin_right_mm` INT NOT NULL DEFAULT 12,
    `margin_bottom_mm` INT NOT NULL DEFAULT 12,
    `margin_left_mm` INT NOT NULL DEFAULT 12,
    `show_clinic_logo` TINYINT(1) NOT NULL DEFAULT 1,
    `show_doctor_signature` TINYINT(1) NOT NULL DEFAULT 1,
    `show_watermark` TINYINT(1) NOT NULL DEFAULT 0,
    `watermark_text` VARCHAR(100) NULL,
    `show_patient_age` TINYINT(1) NOT NULL DEFAULT 1,
    `show_patient_gender` TINYINT(1) NOT NULL DEFAULT 1,
    `show_symptoms_section` TINYINT(1) NOT NULL DEFAULT 1,
    `show_family_history_section` TINYINT(1) NOT NULL DEFAULT 1,
    `show_vitals_section` TINYINT(1) NOT NULL DEFAULT 1,
    `show_findings_section` TINYINT(1) NOT NULL DEFAULT 1,
    `show_diagnosis_section` TINYINT(1) NOT NULL DEFAULT 1,
    `show_qr_code` TINYINT(1) NOT NULL DEFAULT 0,
    `notes` VARCHAR(500) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_prescription_settings_organization` (`organization_id`),
    CONSTRAINT `fk_prescription_settings_organization`
        FOREIGN KEY (`organization_id`) REFERENCES `Organizations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
