DROP TABLE IF EXISTS `shipx_quotation`;

CREATE TABLE `shipx_quotation` (
  `id` int NOT NULL AUTO_INCREMENT,
  `quotation_reference` varchar(40) NOT NULL,
  `customer_request_id` int DEFAULT NULL,
  `request_reference_snapshot` varchar(40) DEFAULT NULL,
  `quotation_title` varchar(255) NOT NULL,
  `service_category` varchar(60) NOT NULL,
  `customer_name` varchar(255) NOT NULL,
  `contact_person` varchar(255) DEFAULT NULL,
  `contact_number` varchar(60) DEFAULT NULL,
  `recipient_email` varchar(255) NOT NULL,
  `origin_location` varchar(255) DEFAULT NULL,
  `destination_location` varchar(255) DEFAULT NULL,
  `cargo_summary` varchar(500) DEFAULT NULL,
  `total_summary_label` varchar(500) DEFAULT NULL,
  `pricing_breakdown_json` text DEFAULT NULL,
  `note_lines_json` text DEFAULT NULL,
  `currency_code` varchar(10) NOT NULL,
  `subtotal_amount` decimal(12,2) NOT NULL,
  `tax_amount` decimal(12,2) DEFAULT NULL,
  `total_amount` decimal(12,2) NOT NULL,
  `valid_until` date NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'DRAFT',
  `email_subject` varchar(255) DEFAULT NULL,
  `email_body` text DEFAULT NULL,
  `sent_to_email` varchar(255) DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `created_by_user_id` int DEFAULT NULL,
  `created_by_user_name` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `flag` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shipx_quotation_reference` (`quotation_reference`),
  KEY `idx_shipx_quotation_customer_request` (`customer_request_id`),
  CONSTRAINT `fk_shipx_quotation_customer_request`
    FOREIGN KEY (`customer_request_id`) REFERENCES `shipx_customer_request` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
