CREATE TABLE IF NOT EXISTS `ClinicSettings` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `organization_id` INT NOT NULL,
    `clinic_name` VARCHAR(150) NOT NULL,
    `clinic_tagline` VARCHAR(150) NULL,
    `doctor_name` VARCHAR(120) NULL,
    `doctor_qualification` VARCHAR(150) NULL,
    `doctor_specialization` VARCHAR(255) NULL,
    `clinic_email` VARCHAR(120) NULL,
    `registration_number` VARCHAR(60) NULL,
    `clinic_address` VARCHAR(255) NULL,
    `appointment_contact` VARCHAR(60) NULL,
    `schedule_line_one` VARCHAR(255) NULL,
    `schedule_line_two` VARCHAR(255) NULL,
    `weekdays_open` TINYINT(1) NOT NULL DEFAULT 1,
    `saturday_open` TINYINT(1) NOT NULL DEFAULT 1,
    `sunday_open` TINYINT(1) NOT NULL DEFAULT 0,
    `opening_time` TIME NOT NULL,
    `closing_time` TIME NOT NULL,
    `break_start_time` TIME NULL,
    `break_end_time` TIME NULL,
    `consultation_fee` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `followup_fee` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `registration_fee` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `medical_certificate_fee` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `base_currency_code` VARCHAR(10) NULL,
    `base_currency_symbol` VARCHAR(10) NULL,
    `base_currency_name` VARCHAR(100) NULL,
    `require_invoice` TINYINT(1) NOT NULL DEFAULT 1,
    `require_medical_certificate` TINYINT(1) NOT NULL DEFAULT 0,
    `reception_token_workflow_enabled` TINYINT(1) NOT NULL DEFAULT 1,
    `slot_duration_minutes` INT NOT NULL DEFAULT 15,
    `notes` VARCHAR(500) NULL,
    `seal_image` LONGBLOB NULL,
    `seal_image_mime_type` VARCHAR(100) NULL,
    `show_official_seal` TINYINT(1) NOT NULL DEFAULT 1,
    `seal_display_mode` VARCHAR(20) NULL DEFAULT 'Header',
    `seal_size_px` INT NOT NULL DEFAULT 96,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_clinic_settings_organization` (`organization_id`),
    CONSTRAINT `fk_clinic_settings_organization`
        FOREIGN KEY (`organization_id`) REFERENCES `Organizations` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
