CREATE TABLE moduleprivileges (
    id INT AUTO_INCREMENT PRIMARY KEY,
    module_id INT NOT NULL,
    submodule_id INT NOT NULL,
    privilege_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
