jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/corex?zeroDateTimeBehavior=convertToNull
jdbc.username=root
jdbc.password=ENC(x9YmUin0h7ohkq7FveO1/YtyO8IW/nqhfuksHWmzivo=)
