log4j.rootLogger=WARN, console

log4j.logger.org.hibernate=WARN
log4j.logger.org.hibernate.SQL=OFF
log4j.logger.org.hibernate.type.descriptor.sql=OFF
log4j.logger.org.hibernate.orm.jdbc.bind=OFF
log4j.additivity.org.hibernate=false

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.Target=System.out
log4j.appender.console.Threshold=WARN
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.logger.com.web.coretix=WARN, coretixFile
log4j.additivity.com.web.coretix=false
log4j.logger.com.module.coretix=WARN, moduleFile
log4j.additivity.com.module.coretix=false
log4j.logger.com.persist.coretix=WARN, persistFile
log4j.additivity.com.persist.coretix=false

log4j.appender.coretixFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.coretixFile.File=${catalina.base}/logs/coretix/coretix.log
log4j.appender.coretixFile.DatePattern='.'dd_MM_yyyy
log4j.appender.coretixFile.layout=org.apache.log4j.PatternLayout
log4j.appender.coretixFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.appender.moduleFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.moduleFile.File=${catalina.base}/logs/coretix/module.log
log4j.appender.moduleFile.DatePattern='.'dd_MM_yyyy
log4j.appender.moduleFile.layout=org.apache.log4j.PatternLayout
log4j.appender.moduleFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

log4j.appender.persistFile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.persistFile.File=${catalina.base}/logs/coretix/persist.log
log4j.appender.persistFile.DatePattern='.'dd_MM_yyyy
log4j.appender.persistFile.layout=org.apache.log4j.PatternLayout
log4j.appender.persistFile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
