CREATE TABLE IF NOT EXISTS Doctors (
    id INT NOT NULL AUTO_INCREMENT,
    organization_id INT NOT NULL,
    user_detail_id INT DEFAULT NULL,
    doctor_code VARCHAR(30) NOT NULL,
    doctor_name VARCHAR(120) NOT NULL,
    qualification VARCHAR(120) DEFAULT NULL,
    specialization VARCHAR(120) DEFAULT NULL,
    license_number VARCHAR(80) DEFAULT NULL,
    phone_number VARCHAR(30) NOT NULL,
    email_address VARCHAR(120) DEFAULT NULL,
    gender VARCHAR(20) DEFAULT NULL,
    consultation_fee DECIMAL(12,2) DEFAULT NULL,
    experience_years INT DEFAULT NULL,
    consultation_duration_minutes INT DEFAULT NULL,
    active BIT NOT NULL DEFAULT b'1',
    notes VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_doctors_doctor_code (doctor_code),
    UNIQUE KEY uk_doctors_user_detail (user_detail_id),
    KEY idx_doctors_org (organization_id),
    CONSTRAINT fk_doctors_organization FOREIGN KEY (organization_id) REFERENCES Organizations(id),
    CONSTRAINT fk_doctors_user_detail FOREIGN KEY (user_detail_id) REFERENCES UserDetails(user_id)
);
